[LA.UM.5.7.r1] Avoid loire logspam by skipping unsupported regulator op
sonyxperiadev/kernel pull request #1436
Opened 2017-09-29 22:53 UTC by oshmoun

on loire devices, gdsc does not support drms, but calls to regulator_set_load are still made.
This is especially problematic in mdss_io_util, where calls are frequent and cause logspam.
Fix it by avoiding the unsupported call if a property in dt is declared.

2017-09-30 02:53 UTC, jerpelea commented
if you use a dt property why do you also ifdef ?
it is enough to check if property is declared!

2017-09-30 06:24 UTC, oshmoun commented
True
I tried to minimize the performance hit on other platforms, but that was probably a bit too overzealous. Especially since the addition is a simple boolean check that shouldn't affect performance. 
Will remove the ifdefs.

2017-09-30 23:15 UTC, kholk commented
Can't we check if the regulator is a gdsc instead?!

2017-09-30 23:58 UTC, oshmoun commented
That should be possible. The dt parsing logic can be replaced with a strcmp call.
We'll still need the new field in the struct this way though.
Also, we'll need to add an ifdef for loire,  since there are gdsc nodes in tone dt.  Afterall, we don't want this change to apply to a platform that isn't affected.

2017-10-01 08:08 UTC, kholk commented
AFAIK, there is no GDSC capable of DRMS..... So... Well, it's curious. 
Let me take a look at this, please hold the PR open for a day or two!

2017-10-01 11:21 UTC, oshmoun commented
just for reference
here are the gdsc nodes for 8996
https://github.com/sonyxperiadev/kernel/blob/aosp/LA.UM.5.7.r1/arch/arm/boot/dts/qcom/msm8996-mdss-pll.dtsi

2017-10-05 10:21 UTC, kholk requested changes

2017-10-05 10:21 UTC, kholk commented on include/linux/mdss_io_util.h
> +	int drms_unsupported;
bool drms_unsupported

2017-10-05 15:40 UTC, aolexiy commented
Instead of introducing yet another property we could pick from mainline, see https://github.com/sonyxperiadev/kernel/pull/1441

The change introduces regulator_ops_is_valid() function to be used as a generic validator and it'll silently skip drms_uA_update call if REGULATOR_CHANGE_DRMS is not supported.

2017-10-05 16:08 UTC, oshmoun commented
The difference is that this approach doesn't modify core Linux API, only the affected drivers.
But the question about how tone isn't affected remains open. Maybe answering that can give an insight as to what's the main cause.

2017-10-09 17:57 UTC, kholk requested changes

2017-10-09 17:57 UTC, kholk commented on drivers/clk/msm/mdss/mdss-pll-util.c
> +		mp->vreg_config[i].drms_unsupported = of_property_read_bool(supply_node,
if regulator rdesc.name contains "gdsc", then drms_unsupported = true;

That's the right way of doing it.

2017-10-09 17:58 UTC, kholk commented on drivers/clk/msm/mdss/mdss-pll-util.c
> +		mp->vreg_config[i].drms_unsupported = of_property_read_bool(supply_node,
P.S.: The regulator name is always "gdsc_xxxx"

2018-03-10 10:05 UTC, closed without merging