[6.4.r1] Import Samsung's exFAT filesystem kernel driver
sonyxperiadev/kernel pull request #1662
Opened 2018-06-09 12:08 UTC by ab123321

Extracted from Samsung Galaxy S8+ SM-G955F open source code release for firmware version G955FXXU2CRED with additional patches.

2018-06-09 12:10 UTC, ab123321 commented
Samsung Galaxy S9 ships with k4.9 and has sdFAT version 2.0.8 that seems compatible with k4.4. Should I merge it or we are going to stick with 1.4.18?

2018-06-09 12:15 UTC, jerpelea commented
use the new driver

2018-06-09 12:17 UTC, luk1337 commented on fs/sdfat/sdfat.c
> +	.name        = "exfat",
no.

2018-06-09 22:13 UTC, kholk commented
Please make a commit with the requested changes.

Also, please add the suggested configuration options in the driver's Kconfig as DEFAULT Y (so, default disallowed). 

Thanks.

2018-06-09 22:14 UTC, kholk commented
P.S.: Sorry about the bad indentation, writing from phone doesn't help!

2018-06-10 18:56 UTC, kholk requested changes

2018-06-10 18:56 UTC, kholk commented on fs/sdfat/core_fat.c
> +
#ifdef CONFIG_SDFAT_DISALLOW_FAT16
return -ENXIO;
#endif

2018-06-10 18:56 UTC, kholk commented on fs/sdfat/core_fat.c
> +	FS_INFO_T *fsi = &(SDFAT_SB(sb)->fsi);
#ifdef CONFIG_SDFAT_DISALLOW_FAT32
return -ENXIO;
#endif

2018-06-10 19:21 UTC, danielgusvt commented
@ab123321 is adding the old driver and after that adding a update commit actually necessary? Would it be possible to import only one commit for the driver?

2018-06-18 11:39 UTC, jerpelea commented
[    1.043772] Registering sdcardfs 0.1
[   11.791278] sdcardfs version 2.0
[   11.791290] sdcardfs: dev_name -> /data/media
[   11.791294] sdcardfs: options -> fsuid=1023,fsgid=1023,multiuser,derive_gid,mask=6,userid=0,gid=1015
[   11.791298] sdcardfs: mnt -> ffffffc0d45cf820
[   11.791333] sdcardfs: mounted on top of /data/media type ext4
[   11.791998] sdcardfs : options - debug:1
[   11.792000] sdcardfs : options - gid:9997
[   11.792002] sdcardfs : options - mask:23
[   11.792535] sdcardfs : options - debug:1
[   11.792537] sdcardfs : options - gid:9997
[   11.792539] sdcardfs : options - mask:7

2018-06-18 11:39 UTC, merged