[7.1.r1] msm: camera: actuator: Fix range for BU64747 actuator
sonyxperiadev/kernel pull request #2118
Opened 2019-12-03 14:12 UTC by kholk

The actuator has a sensible range of 200-800, where 800 is
for near subjects and 200 is "infinity".

Address the userspace framework issues with the actuator range
by normalizing the incoming position request data in the
supported range.

NOTE: THIS IS A WORKAROUND - MOSTLY THE SAME THAT I
PUSHED FOR KERNEL 4.9 BASED BSPs.

THIS IS NOT **THE** SOLUTION (but myopia stops, so feel free
to use it while the camera userspace gets properly fixed/calibrated).

2019-12-03 14:13 UTC, kholk commented
@sraase I don't know whether that was already known or not, but this appears
to be the same issue that we had on the previous k4.9 based CamX.

Tagging you to make you aware of the issue again.

2019-12-04 12:21 UTC, sraase commented
The actual drivers have not changed between CamX versions, so I did not expect any change in behaviour. I hope to be able to investigate this in more detail in the near future.

2019-12-04 16:10 UTC, Thaodan requested changes

2019-12-04 16:10 UTC, Thaodan commented on scripts/kconfig/lxdialog/check-lxdialog.sh
> +	pkg-config $@
If you add command in front of running pkg-config you can just override pkg-config without renaming anything down the line. Or you just define this empty function when ever the above successedes with the name of pkg-config.

2019-12-04 16:10 UTC, Thaodan commented on scripts/kconfig/lxdialog/check-lxdialog.sh
> +pkgconfig()
Rename this to pkg-config and you don't need the other function and you don't need to rename the function calls in ldconfig.

2019-12-04 16:10 UTC, Thaodan commented on scripts/kconfig/lxdialog/check-lxdialog.sh
> +	pkg-config $@
If you use $@ you should quote is or this may break when it gets expanded.

2020-01-09 12:28 UTC, jerpelea commented
for now we add the patch while a solution is investigated

2020-01-09 12:28 UTC, merged