[LA.UM.9.12.r1] treewide: Linux 4.19.148
sonyxperiadev/kernel pull request #2427
Opened 2021-06-10 18:45 UTC by konradybcio

2021-06-10 18:47 UTC, MarijnS95 requested changes
Just like the usual mainline review:

![image](https://user-images.githubusercontent.com/2325264/121580388-facc5900-ca2c-11eb-984a-52f073285e7e.png)


Clarify _why_ changes are made. That way everyone can follow along and confirm eventual observations/claims.

2021-06-10 19:52 UTC, konradybcio commented
After some more showing git who's the boss here it turned out that this revert was in fact not necessary.

2021-06-10 20:13 UTC, MarijnS95 commented
Sounds good, but why is it not squashed in with the relevant patch release where it landed?

2021-06-10 20:13 UTC, MarijnS95 commented
In other words, how can something change from a revert to an "apply"?

2021-06-10 20:14 UTC, konradybcio commented
I skipped it when applying .140 changes and at this point I am kind of scared to mess with git more..

2021-06-10 20:15 UTC, konradybcio commented
I skipped it when applying .140 changes and at this point I am kind of scared to mess with git more..

2021-06-10 20:24 UTC, MarijnS95 commented
```
pick f7c4bb5e394c treewide: Linux 4.19.139
pick 87805ce7ade4 treewide: Linux 4.19.140
f ed1c4a140010 net: refactor bind_bucket fastreuse into helper
pick 325888a897e2 treewide: Linux 4.19.141
pick 978424b4add3 treewide: Linux 4.19.142
pick d40b9516fb44 treewide: Linux 4.19.143
pick 61b8e140d49d treewide: Linux 4.19.144
pick 164b54ed1722 treewide: Linux 4.19.145
pick 19b68dfd15ec treewide: Linux 4.19.146
pick 7ca5ca93d192 treewide: Linux 4.19.147
pick 32cd91230522 treewide: Linux 4.19.148
```

Nothing scary about this.

2021-06-11 18:06 UTC, kholk commented on drivers/base/power/main.c
> -	if (pm_runtime_barrier(dev) && device_may_wakeup(dev))
This is scary and must be tested very .. very carefully

2021-06-11 18:09 UTC, kholk commented on drivers/pci/probe.c
> +static void pci_read_bridge_windows(struct pci_dev *bridge)
Check the modem on EDO, if Qualcomm had fantasy about the hypervisor restrictions, this may KO the platform...

2021-06-28 05:52 UTC, merged