[9.12.r1] Linux stable updates
sonyxperiadev/kernel pull request #2533
Opened 2022-08-25 23:53 UTC by Thaodan

# Description

This PR updates the kernel to the latest linux-stable updates I could apply.
For the latter the are some commits from the android-common kernel needed because of the the backports applied in the android kernel.

# Commits that required manual edits 
Commit conflicts that I needed to resolve (excludes commits without conflicts or manual edits).

## [treewide: 4.19.189](https://github.com/sonyxperiadev/kernel/commit/6468b8ee9874a57dfe8cc08fcafd4c12c5a4658a)

Applied cleanly except:
- 2bd197dfdc913556444ff51670c1c509e725381c skipped because conflicts with downstream
  https://github.com/sonyxperiadev/kernel/commit/fbda00ce1df5b09dbe057af796046b0ded1232f6

## [treewide: 4.19.191](https://github.com/sonyxperiadev/kernel/commit/9cf33b92411e9b5561580349607eaf3291519a2b)

Applied cleanly except:
- 7381dcf620182b4b986894ff36a832de479e1491 skipped since already applied through
  downstream commit https://github.com/sonyxperiadev/kernel/commit/34cc2c83dc809fc1914d499c7b796bb76b58d3e3
- 659ae4a027e2f8538303e700d3374860e330a768 skipped since already
  applied through downstream commit https://github.com/sonyxperiadev/kernel/commit/65873c2988257179a464f896caf0084ba970c77f
- e132c5ca8f64fb9b52434130151a976f82dbfd46 required manual edit
  because of downstream commit https://github.com/sonyxperiadev/kernel/commit/dd914d68a01066757f77cc99d93feb5487481b8e
- 0747a1d043c2c0c062fd40966f642c43247e2477 required manual edit
  because of downstream commit
  https://github.com/sonyxperiadev/kernel/commit/1aacdcf9a11fcabeac8f104a393cb91b4de21cb6 and https://github.com/sonyxperiadev/kernel/commit/a073798a2b5b084ab175ad065010e4658a11d6ab

## [treewide: 4.19.194](https://github.com/sonyxperiadev/kernel/commit/24bb0d9e080f88600e1f096979c5232c9de1c36d)

Applied cleanly, except:
- b5cd7f229609cf328664aedb056a6fd744e0068b required local edit because
  of downstream commit https://github.com/sonyxperiadev/kernel/commit/9475593614eb20f2ff00fa151f2b6b1133893b8e
- 1e9cd487b04f6715c4f14ddd81c5740be852aff2 required local edit because
  of downstream commit https://github.com/sonyxperiadev/kernel/commit/a428dfbf603f417ddb4bd43a7ba39f464498546f

## [treewide: 4.19.195](https://github.com/sonyxperiadev/kernel/commit/239b4adc510dd50bffebadc01751b19a8363b562)

Applied cleanly, except:
- 50316635e644a0b9e62d3263fb4e8be2104605b6 required local edit because
  of downstream commit https://github.com/sonyxperiadev/kernel/commit/df0a8b635b9b1a91a13c56424f7b9289495e6bc2
- 332b827d55f30dd2fdea255db2ba7abb013688d7 required local edit because
  of downstream commit https://github.com/sonyxperiadev/kernel/commit/d2eff574c2ebd5f0e3cec52eba6063f20cf1089d

## [treewide: 4.19.196](https://github.com/sonyxperiadev/kernel/commit/6a32c6d7095b8cae2abb3aa101ce35200fab00ea)

Applied cleanly, except:
- 6edee499192828dc5e885241de12185f5b6df594 already applied as
  https://github.com/sonyxperiadev/kernel/commit/ce3fe8b8cb77778ffd1c51e556de853f51d34cec
- f8111c0d7ed42ede41a3d0d393b104de0730a8a6 required local edit because
  of downstream commit https://github.com/sonyxperiadev/kernel/commit/9d8b19fec3f27bac43b29f6ad8a016fe66560077
- 3bef21035888dd19750ad79b5d08fe52a02ad719 required local edit because
  of downstream commit https://github.com/sonyxperiadev/kernel/commit/2a2a77349a9fbeaace8b130b332c0640c449d3ed
- 7f9745ab342bcce5efd5d4d2297d0a3dd9db0eac required local edit because
  of downstream commit https://github.com/sonyxperiadev/kernel/commit/62523500193e11a8837d4c76ef4a42be2ca4ea0f

## [treewide: 4.19.198](https://github.com/sonyxperiadev/kernel/commit/0158e082abab0c323693da2173640ee36fe30e7a)

Applied cleanly, except:
- 0881aaa1bca6c228871f141b52500fe738f1909a skipped for downstream commit
  https://github.com/sonyxperiadev/kernel/commit/6712d3e2e4c73efb839eee537c04f1e42427a1e2
- 7cb77faedaf57ebb8b5c80e99264998ac977a257 required local edit because
  of downstream commit https://github.com/sonyxperiadev/kernel/commit/281266a3438dddc64d0d8935c97cacab6a150702
- aabde3a07a7900c5114c352103b8e9cd30302ee6 skipped because
  of downstream commit https://github.com/sonyxperiadev/kernel/commit/86eb43f574e090ecb3a2ca7366f4c74bd6ab3df2
- 86f8b0e62ac7cac4423d48ca3d3ba38f2dc5c80d local edit because of
  downstream commit https://github.com/sonyxperiadev/kernel/commit/b660ad7e4f40ead417074141ad8a5a539b532c6a and
  https://github.com/sonyxperiadev/kernel/commit/cb9bad161a3dd993cc12294609587d989d52d335
- https://github.com/sonyxperiadev/kernel/commit/328082376aea6016b63bca1e5c067a9539f9e8c9 local edit because of downstream commit
  https://github.com/sonyxperiadev/kernel/commit/62523500193e11a8837d4c76ef4a42be2ca4ea0f and others

## [treewide: 4.19.205](https://github.com/sonyxperiadev/kernel/commit/a172b26b039db4120ff7e69e0efd921082acfc27)

Applied cleanly, except:
- https://github.com/sonyxperiadev/kernel/commit/afbdcc7c384b0d446da08b1e0901dc176b41b9e0, skipped
- ac8d2c61359c3aca1f3f1c46f2fd3aca4fd4497e, skipped
- ea99a7fae21b554d50880d3392122ffce14615ef, skipped

Reason: Those slimbus patches were not applicable

## [treewide: 4.19.206](https://github.com/sonyxperiadev/kernel/commit/dd145589fce4bebaa035258f745bd25fd81593c5)

Applied cleanly, except:
- 8fc75a3c1de74e892526a38477ae1bfd277d4b3d required local edits
  because of downstream commit https://github.com/sonyxperiadev/kernel/commit/cca3d0b7c7090f1ae264c9724c5ae488eee08033
- c9d60dd3c147c49b3d8eba9aa53ac3b6c24bc161 required local edits
  because of downstream commit https://github.com/sonyxperiadev/kernel/commit/1f805467607ea947f32cd5d7905eadbb4d5df225

## [treewide: 4.19.207](https://github.com/sonyxperiadev/kernel/commit/cf7b674ddedfdd891024e690a5c3d7be200fa9f1)

Applied cleanly, except:
- dd8b408964e77e9b23c4fc6e0cca61bc9345a01f required local edits
  because of downstream commit https://github.com/sonyxperiadev/kernel/commit/b3ef0156f7b325b859bdb98f22acc0b1f182ae2f
- e6c3fefc6bb11bef1bd8adfe37e0f317303ab751 required local edits
  because of downstream commit https://github.com/sonyxperiadev/kernel/commit/de27e1459ea0e7349e210a989490f781ec3ce3c9
- e675870b3625d921a4091063eb61eaf596996730 required local edits
  because of backport applied in https://github.com/sonyxperiadev/kernel/commit/ad8ceb03fd93c01df022454285b882647a477295,
  took later commit https://github.com/sonyxperiadev/kernel/commit/d18760560593e5af921f51a8c9b64b6109d634c2 instead
- 05e4fdd51a934d4bf51b368e5c00dd35f744637e skipped because of deleted
  device tree documentation
- c56350d5bd66da152f6884ab01fcdc199bacfbdb skipped because of
  downstream commit https://github.com/sonyxperiadev/kernel/commit/6b44c854b0f75d8dd1ea7f1d37621cfd82fbd2a9

## [treewide: 4.19.208](https://github.com/sonyxperiadev/kernel/commit/03c5edb2c2a7abfc7191da037fd595c270d6e027)

Applied cleanly, except:
- 3226fb90cf5dc89611f742f122a33d4598076ad5 skipped because change was
  already applied in downstream commit https://github.com/sonyxperiadev/kernel/commit/87988027aec0db3db83843b5d9fa3cd504cf2567

## [treewide: 4.19.209](https://github.com/sonyxperiadev/kernel/commit/d132c782f4a71b48d2dc5895308bdba18108f978)

Applied cleanly, except:
- 30d57cf2c4116ca6d34ecd1cac94ad84f8bc446c required local edit because
  of downstream commit https://github.com/sonyxperiadev/kernel/commit/7a8402647b40512739888718ba358cd0846ec729

## [treewide: 4.19.213](https://github.com/sonyxperiadev/kernel/commit/50df2fe13a63948e05ad4ccbda5245784b9db4b5)

Applied cleanly, except:
- eb0fc8e7170e61eaf65d28dee4a8baf4e86b19ca skipped because of
  downstream commit already applied the change https://github.com/sonyxperiadev/kernel/commit/f54b298454bffd32981288e775ed090ea684ff67

## [treewide: 4.19.214](https://github.com/sonyxperiadev/kernel/commit/fa5c73252e91dc396ec05dfbfdef3c85b5faa233)

Applied cleanly, except:
- 0b7d55ca605e611aceeadf7c29c75808faae951a required local edit
  downstream commit already applied the change https://github.com/sonyxperiadev/kernel/commit/4bd3f510b9373c2ecac6596fc6b8e8ce61d5c7ff

## [treewide: 4.19.218](https://github [...]

2022-08-25 23:53 UTC, Thaodan commented
Each change tested on the Xperia 1 II.

2022-08-26 22:27 UTC, Haxk20 commented
We have kinda setup a rule that we submit 10 upstream versions and test it for a week. If in a week we dont find any regression we apply it and follow up with another set of 10 patches.

But considering we are so heavily behind i would split it into 4 PRs at least still. Its simply far too much to look over in a single PR.

2022-08-26 22:38 UTC, Thaodan commented
> But considering we are so heavily behind i would split it into 4 PRs at least still. Its simply far too much to look over in a single PR.

Sure I can do that, just thinking how much time that will take?

I've been trying to get some kernel updates into a new release.

Plus getting this for up would allow stuff such as lrng.

2022-08-27 08:40 UTC, Haxk20 commented
> > But considering we are so heavily behind i would split it into 4 PRs at least still. Its simply far too much to look over in a single PR.
> 
> Sure I can do that, just thinking how much time that will take?  About the splitting, should I wait or already split the PR?
> 
> I've been trying to get some kernel updates into a new release.
> 
> Plus getting this for up would allow stuff such as lrng.
> 

@jerpelea is the person who decides. I just suggested the split. If he says its ok then yea.

2022-08-28 21:02 UTC, sledges commented
Started testing on Xperia 10 III, looking so far so good on Sailfish OS.

2022-08-29 06:15 UTC, sledges requested changes
Sorry my mistake by flashing the wrong kernel at first.
Image from this PR results in boot-loop on Lena running Sailfish OS 4.4.0 (boot and recovery), so breaking it down into smaller PRs would be easier to bisect the root-cause.

2022-08-29 06:32 UTC, Thaodan commented
> Sorry my mistake by flashing the wrong kernel at first. Image from this PR results in boot-loop on Lena running Sailfish OS 4.4.0 (boot and recovery), so breaking it down into smaller PRs would be easier to bisect the root-cause.

Please attack the contents of /sys/fs/pstore.

2022-08-29 06:37 UTC, sledges commented
:+1: 
[console-ramoops-0.txt](https://github.com/sonyxperiadev/kernel/files/9442084/console-ramoops-0.txt)
[dmesg-ramoops-1.txt](https://github.com/sonyxperiadev/kernel/files/9442085/dmesg-ramoops-1.txt)
[dmesg-ramoops-0.txt](https://github.com/sonyxperiadev/kernel/files/9442086/dmesg-ramoops-0.txt)

2022-08-30 06:29 UTC, jerpelea commented
thanks for the updates. 
If we manage to validate this PR as it is I am ok with merging it but for the future it would be good if we can split the PR in chunks of 10 so that it is easy to review and bisect if issues are found

2022-09-01 23:51 UTC, Thaodan commented
The offending commit https://gitlab.com/linux-kernel/stable/-/commit/f5af297158603dfef42b86d56b751a0799aadbc5 from 4.19.247 will see why it breaks Lena.

2022-09-02 10:26 UTC, Thaodan commented
> The offending commit https://gitlab.com/linux-kernel/stable/-/commit/f5af297158603dfef42b86d56b751a0799aadbc5 from 4.19.247 will see why it breaks Lena.

@jerpelea   @sledges  Fixed now, both Lena and Edo boot fine.

2022-09-04 18:49 UTC, sledges reviewed
It boots now, will use it as daily device.

2022-09-05 07:24 UTC, jerpelea commented
@Thaodan I confirm that the regression is fixed 
please rebase

2022-09-05 08:17 UTC, Thaodan commented
> @Thaodan I confirm that the regression is fixed please rebase

No need to rebase so far.

2022-09-05 08:40 UTC, jerpelea commented
github message "This branch cannot be rebased due to too many changes"

2022-09-05 08:45 UTC, Thaodan commented
Can you merge it without rebase? The first commit already has the last commit the target branch as parent.

2022-09-05 08:46 UTC, jerpelea commented
sure. let me do a manual merge

2022-09-05 09:21 UTC, merged

2022-09-10 20:14 UTC, sledges commented
Daily testing revealed another regression: upper microphone is now being used during normal phone call (through earpiece), which causes loud high-frequency feedback loop. Covering either top-side mic, or earpiece speaker, stops the feedback.

Loudspeaker and headphones mode work fine as before.

2022-09-10 23:41 UTC, Thaodan commented
> Daily testing revealed another regression: upper microphone is now being used during normal phone call (through earpiece), which causes loud high-frequency feedback loop. Covering either top-side mic, or earpiece speaker, stops the feedback.
> 
> Loudspeaker and headphones mode work fine as before.

Found the commit causing the issue, will provide a fix later.

2022-09-11 09:42 UTC, Thaodan commented
The commit that causes the issue is https://github.com/aosp-mirror/kernel_common/commit/9a12fcbf3c622f9bf6b110a873d62b0cba93972e, I'm not exactly sure if the commit is a fault or bad buggy device driver.

2022-10-03 07:15 UTC, jerpelea commented
@Thaodan  please investigate https://github.com/sonyxperiadev/bug_tracker/issues/788

2022-10-11 07:04 UTC, Thaodan commented
> [console-ramoops-0.txt](https://github.com/sonyxperiadev/kernel/files/9442084/console-ramoops-0.txt)
> [dmesg-ramoops-1.txt](https://github.com/sonyxperiadev/kernel/files/9442085/dmesg-ramoops-1.txt)
> [dmesg-ramoops-0.txt](https://github.com/sonyxperiadev/kernel/files/9442086/dmesg-ramoops-0.txt)
> 
 

I could reproduce the issues and I'm bisecting it now.